### ISSUE TITLE
[envs] SimpleMaze, component removed

### ISSUE THREAD

**Issue by hunoutl** [SofaDefrost/SofaGym#11]
SimpleMaze contains components that have been removed from Sofa.
I tried some tweaks on the sphere object but it wasn't great and this is only the 1st mistake of this type. I think this scene has others.
The error output:

```
[ERROR]   [SofaRuntime] ValueError: Object type Sphere<> was not created  
The object is not in the factory.  
This component has been REMOVED since SOFA v20.06 (deprecated since v19.12). Please consider updating your scene. If this component is crucial to you please report that to sofa-dev@ so that we can reconsider this component for future re-integration.  

Traceback (most recent call last):
  File "/home/hunoutl/SOFA/SofaGym/sofagym/rpc_client.py", line 174, in <module>
    root = init_simulation(config, _startCmd, mode='simu')
  File "/home/hunoutl/SOFA/SofaGym/sofagym/simulate.py", line 49, in init_simulation
    create_scene(root,  config, mode = mode)
  File "/home/hunoutl/SOFA/SofaGym/sofagym/envs/SimpleMaze/SimpleMazeScene.py", line 86, in createScene
    sphere.addObject("Sphere", radius='2.0', name='0', color=[255, 0, 0, 255])
```

```
[ERROR]   [SofaRuntime] ValueError: Object type Triangle<> was not created  
The object is not in the factory.  
This component has been REMOVED since SOFA v20.06 (deprecated since v19.12). Please consider updating your scene. If this component is crucial to you please report that to sofa-dev@ so that we can reconsider this component for future re-integration.  

Traceback (most recent call last):
  File "/home/hunoutl/SOFA/SofaGym/sofagym/rpc_client.py", line 174, in <module>
    root = init_simulation(config, _startCmd, mode='simu')
  File "/home/hunoutl/SOFA/SofaGym/sofagym/simulate.py", line 49, in init_simulation
    create_scene(root,  config, mode = mode)
  File "/home/hunoutl/SOFA/SofaGym/sofagym/envs/SimpleMaze/SimpleMazeScene.py", line 118, in createScene
    maze.addObject("Triangle", group=1)
```

**Comment by alxbilger** [comment]
Try with `SphereModel` and `TriangleModel`

**Comment by hunoutl** [comment]
Like this ?
` sphere.addObject("SphereModel", radius='2.0', name='0', color=[255, 0, 0, 255])`
Doesn't work
