### ISSUE TITLE
problem with sofagym

### ISSUE THREAD

**Issue by Abdelrahman-Alkhodary** [SofaDefrost/SofaGym#15]
Hello all

I'm trying to run sofagym but I'm getting this error as in #12 

`
[ERROR]   [SofaRuntime] AttributeError: Missing attribute: addNewData
Traceback (most recent call last):
  File "e:\sofa\sofagym\sofagym/sofagym/rpc_client.py", line 174, in <module>
    root = init_simulation(config, _startCmd, mode='simu')
  File "e:\sofa\sofagym\sofagym\sofagym\simulate.py", line 49, in init_simulation
    create_scene(root,  config, mode = mode)
  File "e:\sofa\sofagym\sofagym\sofagym\envs\Trunk\TrunkScene.py", line 214, in createScene
    trunk = Trunk(simulation, inverseMode=False)
  File "E:\SOFA\SOFA_v22.06.00_Win64\plugins\STLIB\lib\python3\site-packages\splib3\objectmodel\__init__.py", line 49, in __call__
    o.node.addNewData("Prefab type", "Infos", "","string", str(o.__class__.__name__))
`

When I change the addNewData to addData inside the splib3 I got this error

`
[ERROR]   [SofaRuntime] TypeError: Invalid Type string: available types are
[Edge, Hexa, Link, Mat2x2d, Mat2x2f, Mat3x3d, Mat3x3f, Mat3x4d, Mat3x4f, Mat4x4d, Mat4x4f, Penta, PrefabLink, Quad, Rigid3::VecCoord, Rigid3d::VecCoord, Rigid3f::VecCoord, Tetra, Triangle, Vec2d, Vec2f, Vec3d, Vec3f, Vec4d, Vec4f, Vec6d, Vec6f, bool, double, float, int, string, vector<Edge>, vector<Hexa>, vector<Mat2x2d>, vector<Mat2x2f>, vector<Mat3x3d>, vector<Mat3x3f>, vector<Mat3x4d>, vector<Mat3x4f>, vector<Mat4x4d>, vector<Mat4x4f>, vector<Penta>, vector<Quad>, vector<Tetra>, vector<Triangle>, vector<Vec2d>, vector<Vec2f>, vector<Vec3d>, vector<Vec3f>, vector<Vec4d>, vector<Vec4f>, vector<Vec6d>, vector<Vec6f>, vector<bool>, vector<double>, vector<float>, vector<int>, vector<string>]
Traceback (most recent call last):
  File "e:\sofa\sofagym\sofagym/sofagym/rpc_client.py", line 174, in <module>
    root = init_simulation(config, _startCmd, mode='simu')
  File "e:\sofa\sofagym\sofagym\sofagym\simulate.py", line 49, in init_simulation
    create_scene(root,  config, mode = mode)
  File "e:\sofa\sofagym\sofagym\sofagym\envs\Trunk\TrunkScene.py", line 214, in createScene
    trunk = Trunk(simulation, inverseMode=False)
  File "E:\SOFA\SOFA_v22.06.00_Win64\plugins\STLIB\lib\python3\site-packages\splib3\objectmodel\__init__.py", line 49, in __call__
    o.node.addData("Prefab type", "Infos", "","string", str(o.__class__.__name__))
`

Can any one tell how to solve this issue please?

I'm runnign Sofa 22.06 on windows 10

**Comment by alxbilger** [comment]
Hi,

I don't think you correctly used the `addData` method. Here is my suggestion: https://github.com/SofaDefrost/STLIB/pull/92/commits/353658f48ae45479f61aa042fc0c92e028f42553

Let us know if it worked.

Alex

**Comment by Abdelrahman-Alkhodary** [comment]
Hello @alxbilger your solution solved the issue, but when I try to run this simple code 

```
import gym
import sofagym.envs
env = gym.make('trunk-v0')
env.reset()
```
I got this error

```
[ERROR]   [SofaRuntime] ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "e:\sofa\sofagym\sofagym/sofagym/rpc_client.py", line 181, in <module>
    task = s.getNextTask(stateId)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\xmlrpc\client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\xmlrpc\client.py", line 1450, in __request
    response = self.__transport.request(
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\xmlrpc\client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\xmlrpc\client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\xmlrpc\client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\xmlrpc\client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\http\client.py", line 951, in send
    self.connect()
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\http\client.py", line 922, in connect
    self.sock = self._create_connection(
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\Abdulrahman Helmy\anaconda3\envs\sofa-gym\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
```

so I tried another code to run which you have in readme

```
env = gym.make('trunk-v0')
observation = env.reset()

done = False
while not done:
    action = env.action_space.sample()  # this is where you would insert your policy
    observation, reward, done, info = env.step(action)
    env.render()

env.close()
```

I got this error

```
 KeyError: 'dt'
Traceback (most recent call last):
  File "e:\sofa\sofagym\sofagym/sofagym/rpc_client.py", line 188, in <module>
    do_animate(task, _getReward, _getState, _startCmd, _getPos)
  File "e:\sofa\sofagym\sofagym/sofagym/rpc_client.py", line 87, in do_animate
    pos = step_simulation(root, config, action, _startCmd, _getPos)
  File "e:\sofa\sofagym\sofagym\sofagym\simulate.py", line 111, in step_simulation
    _startCmd(root, action, config["dt"]*(config["scale_factor"]-1))
```

sorry for too many errors and any inconvience

**Comment by EtienneMenager** [comment]
Hi, 

You can add the "dt" argument in your environment. Please go to your TrunkEnv.py and add "dt":0.01 in the config. It will solve the issue. 

@hunoutl the "dt" is needed in the file simulate.py l.111 but it is not in the config of the envs

Etienne

**Comment by hunoutl** [comment]
Recorded, it will be added & checked in all envs in futur PR

**Comment by Abdelrahman-Alkhodary** [comment]
I added the dt to config as you advised @EtienneMenager and it solved the issue, but when the pygame window appears it freezes immediately. When I close it,  it gave me the same connection error as above  [WinError 10061]

**Comment by EtienneMenager** [comment]
It seems that there were several times this problem of connection with Window. Can anyone with Window test the connection and sofagym on this platform? @alxbilger @hunoutl

**Comment by hunoutl** [comment]
> It seems that there were several times this problem of connection with Window. Can anyone with Window test the connection and sofagym on this platform? @alxbilger @hunoutl

I will make a try.

**Comment by alxbilger** [comment]
@Abdelrahman-Alkhodary Do you have more feedback to share?

**Comment by Abdelrahman-Alkhodary** [comment]
Hello @alxbilger 

I haven't tried it since, I will colse the issue and if I have any more questions I will make sure to ask. Thanks
